export 'package:flutter/material.dart';
export 'package:firebase_core/firebase_core.dart';
export 'package:firebase_auth/firebase_auth.dart';
export 'package:font_awesome_flutter/font_awesome_flutter.dart';
export 'package:shared_preferences/shared_preferences.dart';
export '/pages/homepage.dart';
export '/pages/splash.dart';
export '/pages/login.dart';
export '/pages/signup.dart';