// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyARSHDV5ej2wskbooVAlvRmM--3w0YTef8',
    appId: '1:23593107175:web:a09d70180d8c923eacac42',
    messagingSenderId: '23593107175',
    projectId: 'patogtog-b2454',
    authDomain: 'patogtog-b2454.firebaseapp.com',
    storageBucket: 'patogtog-b2454.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDpyYpBZWrqCJn1cVivFBzvhI9tAg3S4JI',
    appId: '1:23593107175:android:08894353bc4bdcceacac42',
    messagingSenderId: '23593107175',
    projectId: 'patogtog-b2454',
    storageBucket: 'patogtog-b2454.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCa61VlqmXbYn0tTzBFGRTX1UkauE51pI4',
    appId: '1:23593107175:ios:7ce41de137c13c37acac42',
    messagingSenderId: '23593107175',
    projectId: 'patogtog-b2454',
    storageBucket: 'patogtog-b2454.appspot.com',
    iosBundleId: 'com.example.finalproject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCa61VlqmXbYn0tTzBFGRTX1UkauE51pI4',
    appId: '1:23593107175:ios:7ce41de137c13c37acac42',
    messagingSenderId: '23593107175',
    projectId: 'patogtog-b2454',
    storageBucket: 'patogtog-b2454.appspot.com',
    iosBundleId: 'com.example.finalproject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyARSHDV5ej2wskbooVAlvRmM--3w0YTef8',
    appId: '1:23593107175:web:5b9db2015850abe7acac42',
    messagingSenderId: '23593107175',
    projectId: 'patogtog-b2454',
    authDomain: 'patogtog-b2454.firebaseapp.com',
    storageBucket: 'patogtog-b2454.appspot.com',
  );
}
